#!/bin/bash

set -e

DOT_EXPORTS=/home/edimarsa/.config/.exports
if [ -f "$DOT_EXPORTS" ]; then
    # shellcheck source=/dev/null
    . "$DOT_EXPORTS"
fi

KEY_BINDINGS=/usr/share/doc/fzf/examples/key-bindings.bash
if [ -f "$KEY_BINDINGS" ]; then
    # shellcheck source=/dev/null
    source "$KEY_BINDINGS"
fi
