#!/bin/bash

set -e

DOT_EXPORTS=/home/edimarsa/.config/.exports
if [ -f "$DOT_EXPORTS" ]; then
    # shellcheck source=/dev/null
    . "$DOT_EXPORTS"
fi

if [ -f /usr/share/doc/fzf/examples/key-bindings.bash ]; then
    # shellcheck source=/dev/null
    source /usr/share/doc/fzf/examples/key-bindings.bash
fi
if [ -f /usr/share/doc/fzf/examples/key-bindings.bash ]; then
    # shellcheck source=/dev/null
    source /usr/share/doc/fzf/examples/key-bindings.bash
fi
