#! /bin/bash

# Github
export GITHUB_USERNAME="EdimarMngs"
export DEV_CONTAINER=0
export EDITOR=code
export MNG_CFGDIR=/home/edimarsa/config

if [ -d "$HOME/scripts/personal_functions" ]; then
    export PATH="$PATH:$HOME/scripts/personal_functions"
fi
